
[http]
addr = ":9999"

[auth]
aesTokenKey = "9Nz3Y6DES3msAFndz4QsJAECUIFkf+KKaRa+jRnNALk="
ignoreUrl = [
    "/api/conn/ws",
    "/api/conn/opMap",
    "/api/auth/captcha",
    "/api/auth/authorize",
    "/api/user/findByName",
]
# 需要输入图形验证码的url
captchaUrl = [
    "/auth/authorize"
]

[sqlite]
dbPath = "etc/texas-poker.db"

[game]
# 新用户赠送筹码
GiftChip = 10000
